<a href="https://colab.research.google.com/github/emish8/image-processing-application-using-opencv-flask-and-fluttlerflow/blob/main/Functions_and_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install flask-ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from flask_ngrok import run_with_ngrok
import cv2
import matplotlib.pyplot as plt
import numpy as np
import werkzeug
from flask import Flask, jsonify, request
import urllib.request
from PIL import Image, ImageFilter
import os

In [ ]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 761 kB 7.7 MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.2.1-py3-none-any.whl size=19792 sha256=cf4e9b8ba75c12ea2c0039c87721dfaaa6fec085e284b4d46056e7ab2a751505
  Stored in directory: /root/.cache/pip/wheels/5d/f2/70/526da675d32f17577ec47ac4c663084efe39d47c826b6c3bb1
Successfully built pyngrok


In [ ]:
!ngrok authtoken  2HUgjQxobVhhhggZlbYJ3PLhmWvggLXhc_42kaKhgCB1BtH4YNuWkghkliudkr  # dummy token (use your own)

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
!pip install firebase

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install pyrebase

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Upload Function

In [ ]:
# For Firebase JS SDK v7.20.0 and later, measurementId is optional

import pyrebase
import os
import cv2


def upload(img):
  """"
  This function takes processed image, uploads it on firebase and returns image url
  that can be used to access the image.
  
  img : numpy array

  retruns
  url : a public url of the processed image
  """"
  
  

  # you can find these configuration values of firebase, go to project overview > project web > SDK setup and configuration
  # Make sure to strat your real time database
  # dummy values
  config = {
  "apiKey": "SyBsaqmUWqy6Hvvv0sGUFjrhqEAZJALfy4zEy94",
  "authDomain": "pixel.firebaseapp.com",
  "databaseURL": "https://pixel.firebaseio.com",
  "projectId": "pixel",
  "storageBucket": "pixel.appspot.com",
  "messagingSenderId": "854311134741683",
  "appId": "1:853741683:web:9ccbaf874656cc5e0e5c6",
  "measurementId": "G-3VM56HSWDG"}

  firebase = pyrebase.initialize_app(config)
  storage = firebase.storage()
  img = cv2.imwrite("/content/output.jpg",img)
  # Upload Image
  upload = storage.child("output.jpg").put("output.jpg")

  url = storage.child("output.jpg").get_url(upload["downloadTokens"])

  return url


# Image Processing Functions By Group Members

In [ ]:

#Aneri- Morphology 


# Read function
#def readImage(img):
 #   return cv2.imread(img)

#img = cv2.imread("img.jpg")

# Kernel Function
def kernelFunc(size):
    return np.ones((size, size), np.uint8)


# Orignal Image
def orignalImage(img):
    rgb_image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return rgb_image


# Erosion Matrix Function
def matrixEro(img, size_of_kernel=3, no_of_iterations=5):
    orignal_image = orignalImage(img)
    erosion = cv2.erode(orignal_image, kernel=kernelFunc(size_of_kernel), iterations=no_of_iterations)
    return erosion


# Dilation Matrix Function
def matrixDil(img, size_of_kernel=3, no_of_iterations=5):
    orignal_image = orignalImage(img)
    dilation = cv2.dilate(orignal_image, kernel=kernelFunc(size_of_kernel), iterations=no_of_iterations)
    return dilation


# Gradient Matrix Function
def matrixGrad(img, size_of_kernel=3, no_of_iterations=5):
    gradient = matrixEro(img, size_of_kernel, no_of_iterations) - matrixDil(img, size_of_kernel, no_of_iterations)
    return gradient


# Opening  Matrix Function
def matrixOpening(img, size_of_kernel=3, no_of_iterations=5):
    erosion_image = matrixEro(img, size_of_kernel, no_of_iterations)
    opening_image = cv2.dilate(erosion_image, kernel=kernelFunc(size_of_kernel), iterations=no_of_iterations)
    return opening_image


# Closing Matrix Function
def matrixClosing(img, size_of_kernel=3, no_of_iterations=5):
    orignal_image = orignalImage(img)
    dilation_image = matrixDil(img, size_of_kernel, no_of_iterations)
    closing_image = cv2.erode(dilation_image, kernel=kernelFunc(size_of_kernel), iterations=no_of_iterations)
    return closing_image


# Black Hat Matrix Function
def matrixBlackHat(img, size_of_kernel=3, no_of_iterations=5):
    orignal_image = orignalImage(img)
    closing_img = matrixClosing(img, size_of_kernel, no_of_iterations)
    black_hat = closing_img - orignal_image
    return black_hat


# Top Hat Matrix Function
def matrixTopHat(img, no_of_iterations=5, size_of_kernel=3, no_tophat_iterations=6):
    orignal_image = orignalImage(img)
    opening_image = matrixOpening(img, no_of_iterations, size_of_kernel)
    for i in range(0, no_tophat_iterations):
        top_hat = orignal_image - opening_image
        top_hat
    return top_hat


# Plot All in one Function
def plotAll(img, size_of_kernel=3, no_of_iterations=5, no_tophat_iterations=6):
    orig_img = orignalImage(img)
    ero_img_1 = matrixEro(img, size_of_kernel, no_of_iterations)
    dil_img_2 = matrixDil(img, size_of_kernel, no_of_iterations)
    gra_img_3 = matrixGrad(img, size_of_kernel, no_of_iterations)
    ope_img_4 = matrixOpening(img, size_of_kernel, no_of_iterations)
    clo_img_5 = matrixClosing(img, size_of_kernel, no_of_iterations)
    bla_img_6 = matrixBlackHat(img, size_of_kernel, no_of_iterations)
    top_img_7 = matrixTopHat(img, no_of_iterations, size_of_kernel, no_tophat_iterations)
    imglist = [orig_img, ero_img_1, dil_img_2, gra_img_3, ope_img_4, clo_img_5, bla_img_6, top_img_7]

    fig, ax = plt.subplots(4, 2, figsize=(8, 8), facecolor="w", tight_layout=True)
    plt.subplots_adjust(left=0.01,
                        bottom=0.01,
                        right=0.9,
                        top=0.9,
                        wspace=0.4,
                        hspace=0.4)

    ax[0, 0].imshow(imglist[0])
    ax[0, 0].set_title("Orignal Image")
    ax[0, 0].set_xticklabels(labels="", rotation=90, c="w", fontweight="bold", fontsize=12)
    ax[0, 0].set_yticklabels(labels="", rotation=360, c="w", fontweight="bold", fontsize=12)

    ax[0, 1].imshow(imglist[1])
    ax[0, 1].set_title("Erosion Image")
    ax[0, 1].set_xticklabels(labels="", rotation=90, c="w", fontweight="bold", fontsize=12)
    ax[0, 1].set_yticklabels(labels="", rotation=360, c="w", fontweight="bold", fontsize=12)

    ax[1, 0].imshow(imglist[2])
    ax[1, 0].set_title("Dilation Image")
    ax[1, 0].set_xticklabels(labels="", rotation=90, c="w", fontweight="bold", fontsize=12)
    ax[1, 0].set_yticklabels(labels="", rotation=360, c="w", fontweight="bold", fontsize=12)

    ax[1, 1].imshow(imglist[3])
    ax[1, 1].set_title("Gradient Image")
    ax[1, 1].set_xticklabels(labels="", rotation=90, c="w", fontweight="bold", fontsize=12)
    ax[1, 1].set_yticklabels(labels="", rotation=360, c="w", fontweight="bold", fontsize=12)

    ax[2, 0].imshow(imglist[4])
    ax[2, 0].set_title("Opening Image")
    ax[2, 0].set_xticklabels(labels="", rotation=90, c="w", fontweight="bold", fontsize=12)
    ax[2, 0].set_yticklabels(labels="", rotation=360, c="w", fontweight="bold", fontsize=12)

    ax[2, 1].imshow(imglist[5])
    ax[2, 1].set_xticklabels(labels="", rotation=90, c="w", fontweight="bold", fontsize=12)
    ax[2, 1].set_yticklabels(labels="", rotation=360, c="w", fontweight="bold", fontsize=12)
    ax[2, 1].set_title("Closing Image")

    ax[3, 0].imshow(imglist[6])
    ax[3, 0].set_xticklabels(labels="", rotation=90, c="w", fontweight="bold", fontsize=12)
    ax[3, 0].set_yticklabels(labels="", rotation=360, c="w", fontweight="bold", fontsize=12)
    ax[3, 0].set_title("Black Hat Image")

    ax[3, 1].imshow(imglist[7])
    ax[3, 1].set_xticklabels(labels="", rotation=90, c="w", fontweight="bold", fontsize=12)
    ax[3, 1].set_yticklabels(labels="", rotation=360, c="w", fontweight="bold", fontsize=12)
    ax[3, 1].set_title("Top Hat Image")

    plt.savefig("abc.png", dpi=1000, bbox_inches='tight')
    img_rtr = cv2.imread("abc.png")
    img_rtr = cv2.cvtColor(img_rtr, cv2.COLOR_BGR2RGB)
    os.remove("abc.png")

    return img_rtr






In [ ]:
#erosion
def erosion(img):
    k = np.ones((5,5)).astype(int)
    erosion = cv2.erode(img, kernel = k, iterations= 1)
    return  erosion

In [ ]:
#kinjal- bilatral
def bilateral_filter(img):
    #img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    bilateral = cv2.bilateralFilter(img, 15, 85, 80)
    #output=plt.imshow(bilateral)
    return bilateral


In [ ]:
#vishwa patel- smoothing filter
def smoothing(img,fltr= "MedianBlur"):  

    #img1 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    if fltr == "GaussianBlur":
        title = "GaussianBlur"
        output = cv2.GaussianBlur(img,(5,5),sigmaX=0)
    else :
        title = "medianBlur"
        output = cv2.medianBlur(img,ksize=5)
    return output
    

In [ ]:
#Vibhuti- threshold
def thresh(img):
    
    #img1 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    grayimage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, binary = cv2.threshold(grayimage, 100, 255, cv2.THRESH_BINARY)
    ret, binaryinv = cv2.threshold(grayimage, 100, 255, cv2.THRESH_BINARY_INV)
    ret, trunc = cv2.threshold(grayimage, 100, 255, cv2.THRESH_TRUNC)
    ret, tozero = cv2.threshold(grayimage, 100, 255, cv2.THRESH_TOZERO)
    ret, tozeroinv = cv2.threshold(grayimage, 100, 255, cv2.THRESH_TOZERO_INV)
    adaptive_thresh1 = cv2.adaptiveThreshold(grayimage, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 11, 2)
    adaptive_thresh2 = cv2.adaptiveThreshold(grayimage, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2)

    
    thresh_output= binaryinv
    
    return thresh_output




In [ ]:
#devangee- harris corner detection
def HarrisCorner(img):
    operatedImage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    operatedImage = np.float32(operatedImage)
    dest = cv2.cornerHarris(operatedImage, 2, 5, 0.07)
    dest = cv2.dilate(dest, None)
    img[dest > 0.01 * dest.max()]=[0, 0, 255]
    #output=plt.imshow(dest, cmap='gray')
    harris_output=img
    return harris_output


In [ ]:
# MUSKAN- Canny Edge Detection
def CannyEdge(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    blur = cv2.GaussianBlur(gray, (3, 3), 0) # help of GussianBlur
    edge = cv2.Canny(blur, 10, 100)
    #output=plt.imshow(edge)
    return edge

In [ ]:
#Vishwa Soni : Image enhancement Contrast Streching 

def preprocessing(img):
    # resizing using aspect ratio intact and finding the circle
    # reduce size retain aspect ratio intact
    # invert BGR 2 RGB
    RGB = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    Ig = RGB[:, :, 2]
    [w,h] = np.shape(Ig)
    r=1200.0/Ig.shape[1]
    dim=(1200,int(Ig.shape[0]*r))
    rz = cv2.resize(Ig,dim,interpolation=cv2.INTER_AREA)
    #  convert in to float and get log trasform for contrast streching
    g = 0.2 * (np.log(1 + np.float32(rz)))
    # change into uint8
    cvuint = cv2.convertScaleAbs(g)
    # cvuint8.dtype
    ret, th = cv2.threshold(cvuint, 0, 255, cv2.THRESH_OTSU)
    ret1,th1 = cv2.threshold(Ig,0,255,cv2.THRESH_OTSU)
    # closeing operation
    # from skimage.morphology import disk
    # from skimage.morphology import erosion, dilation, opening, closing, white_tophat
    # selem = disk(30)
    # cls = opening(th, selem)
    # plot_comparison(orig_phantom, eroded, 'erosion')
    # in case using opencv
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (35,35))
    cls = cv2.morphologyEx(th, cv2.MORPH_OPEN, kernel)
    Im = cls*rz # the mask with resize image
    # cv2.imwrite('mynew.jpg', mask)
    #output=plt.imshow(g,cmap='gray')
    return Im

In [ ]:
#Khushi Sagar- DOWNSAMPLE-Lower Resolution

def lower_reso(img):
    rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    grayimage = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
    lower_reso = cv2.pyrDown(rgb)
    #output=plt.imshow(lower_reso, cmap="gray")
    return lower_reso

In [ ]:
#FORAM- Rotation

def combine (img):
    img1 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    grayimage = cv2.cvtColor(img1, cv2.COLOR_RGB2GRAY)

    res = cv2.resize(grayimage,None,fx=2, fy=4, interpolation = cv2.INTER_CUBIC)

    # height, width = img.shape[:2]
    # res = cv2.resize(grayimage,(2*width, 4*height), interpolation = cv2.INTER_CUBIC)

    rows, cols = grayimage.shape

    M1 = np.float32([[1,0,-100],[0,1,-100]])
    dst1 = cv2.warpAffine(grayimage, M1, (cols, rows))

    M2 = cv2.getRotationMatrix2D((cols/2,rows/2),90,1)
    dst2 = cv2.warpAffine(grayimage,M2,(cols,rows))

    pts11 = np.float32([[50,50],[200,50],[50,200]])
    pts12 = np.float32([[10,100],[200,50],[100,250]])
    M3 = cv2.getAffineTransform(pts11,pts12)
    dst3 = cv2.warpAffine(grayimage,M3,(cols,rows))


    pts21 = np.float32([[50,50],[550,50],[50,550],[550,550]])
    pts22 = np.float32([[0,0],[500,0],[0,500],[500,500]])
    M4 = cv2.getPerspectiveTransform(pts21,pts22)
    dst4 = cv2.warpPerspective(grayimage,M4,(500,500))

    
    #output=plt.imshow(dst2, cmap="gray"),plt.title("Rotation")
    #plt.xticks([]), plt.yticks([])
    return dst2

In [ ]:
#Aarti -Laplacian sharpen filter
def laplacian(img):
    sharpen_kernel = np.array([[0, -1, 0],
                          [-1, 5, -1],
                          [0, -1, 0]])
    laplacian = cv2.filter2D(src=img,ddepth=-1,kernel = sharpen_kernel)
    #plt.figure(figsize=(5,3))
    #output=plt.imshow(laplacian)
    return laplacian

In [ ]:
#KASHISH- RGB to GRAY
def RgbGray(img, dist_val = 175, max_val=50):
       
        fix_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        
        R, G, B = fix_img[:,:,0], fix_img[:,:,1],fix_img[:,:,2]
    
        grayscale_weighted_img = 0.299 * R + 0.5878 * G + 0.114 * B
        return grayscale_weighted_img

In [ ]:
#Bansi - (Hough transform)
import math 

def LineDetection(img):
    dst = cv2.Canny(img, 50, 200, None, 3)
    
    # Copy edges to the images that will display the results in BGR
    cdst = cv2.cvtColor(dst, cv2.COLOR_GRAY2BGR)
    cdstP = np.copy(cdst)
    
    lines = cv2.HoughLines(dst, 1, np.pi / 180, 150, None, 0, 0)
    
    if lines is not None:
        for i in range(0, len(lines)):
            rho = lines[i][0][0]
            theta = lines[i][0][1]
            a = math.cos(theta)
            b = math.sin(theta)
            x0 = a * rho
            y0 = b * rho
            pt1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))
            pt2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))
            cv2.line(cdst, pt1, pt2, (0,0,255), 3, cv2.LINE_AA)
    
    
    linesP = cv2.HoughLinesP(dst, 1, np.pi / 180, 50, None, 50, 10)
    
    if linesP is not None:
        for i in range(0, len(linesP)):
            l = linesP[i][0]
            cv2.line(cdstP, (l[0], l[1]), (l[2], l[3]), (0,0,255), 3, cv2.LINE_AA)
    
    return cdstP

In [ ]:
#Jinal (Convolution function)
def gaussianBlur(img):
    
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    gaussianBlur = cv2.GaussianBlur(img,(7,7),0)
    return gaussianBlur

In [ ]:
#Keya
# from PIL import Image,ImageFilter

# def min_filter(img):
#     '''Minimum filter applied on the image'''
#     #img = Image.open(img)
#     img = Image.fromarray(img.astype('uint8'))
#     min_img = img.filter(ImageFilter.MinFilter(size = 3))
#     #output = plt.imshow(min_img)
#     #plt.xticks([])
#     #plt.yticks([])
#     return min_img

def min_filter(img):
  '''Minimum filter applied on the image'''
  size = (3,3)
  shape = cv2.MORPH_RECT
  kernel = cv2.getStructuringElement(shape, size)
  imgResult = cv2.erode(img, kernel)
  return imgResult

In [ ]:
#Zeel Rathi Watershed Function

def watershed(img):
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU) #thresholding the imae using otsu's binarization
    kernel = np.ones((3, 3), np.uint8)
    thresh = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel, iterations=2) # Removing small regions
    extendedFg = cv2.dilate(thresh, kernel, iterations=2)
    distance = cv2.distanceTransform(thresh, cv2.DIST_L2, 5)# foreground centers
    ret, fgCenters = cv2.threshold(distance, 0.7 * distance.max(), 255, 0)
    fgCenters = np.uint8(fgCenters)  # unknown regions subtracting the foreground centers to the extended foreground
    unknown = cv2.subtract(extendedFg, fgCenters)
    ret, markers = cv2.connectedComponents(fgCenters) #defining the markers
    markers = markers + 1
    markers[unknown == 255] = 0 # marking the unknown regions with zero
    markers = cv2.watershed(img, markers)  # applying the method
    img[markers == -1] = [255, 0, 0]  # draw the boundary regions marked with -1 , ont the original image
   
    #output=plt.imshow(markers),plt.title("watersheded image")
   
    return extendedFg

# API

In [ ]:
app = Flask(__name__)
run_with_ngrok(app)  



def read_img(url):
  req = urllib.request.urlopen(url)
  arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
  img = cv2.imdecode(arr, -1) 

  return  cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  

@app.route('/', methods=['POST','GET'] )
def convert():
   
    if(request.method == "POST"):
      print('got post request')
      data = request.get_json()
      print(data)
      try:
        image_path = data['img_path']
        img =  read_img(image_path)
       
      except:
        print('image path error')

      try:
        opr = data['operation']
        print(opr)

      except:
        print('operation error')

      if opr == 'erosion':
        output = erosion(img)
        print("erosion called", output)
        plt.imshow(output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}

        
      #Aneri - Morphology
      elif opr == 'morphology':
        output = plotAll(img, size_of_kernel=3, no_of_iterations=5, no_tophat_iterations=6)
        print("morphology called", output)
        #plt.imshow(output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}


      
      # Kinjal-bilateral
      elif opr == 'bilateral':
        output = bilateral_filter(img)
        print("bilateral called", output)
        #plt.imshow(output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}
      
      # Vishwa Patel - SMOOTHING 
      elif opr == 'smoothing':
        output = smoothing(img)
        print("smoothing called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}
        
      #Vibhuti- threshold
      elif opr == 'thresh':
        output = thresh(img)
        print("thresh called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}

      #devangee- harris corner detection
      elif opr == 'harris':
        output = HarrisCorner(img)
        print("harris called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True} 

   
      #MUSKAN- Canny Edge Detection
      elif opr == 'canny':
        output = CannyEdge(img)
        print("canny called", output)
        output_url = upload(output)
        print('output_url',output_url)
        return  {"output": output_url,"status":True} 

      

     
      #Vishwa Soni : Image enhancement Contrast Streching
      elif opr == 'preprocessing':
        output = preprocessing(img)
        print("preprocessing called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True} 

      

      #Khushi Sagar- DOWNSAMPLE-Lower Resolution
      elif opr == 'lower_reso':
        output = lower_reso(img)
        print("lower_reso called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True} 

      #FORAM- Rotation
      elif opr == 'rotate':
        output = combine(img)
        print("rotate called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True} 


      #Aarti -Laplacian sharpen filter
      elif opr == 'laplacian':
        output = laplacian(img)
        print("laplacian called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}



      #KASHISH- RGB to GRAY
      elif opr == 'RgbGray':
        output = RgbGray(img)
        print("RgbGray called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}


      
      #Bansi - (Hough transform)
      elif opr == 'LineDetection':
        output = LineDetection(img)
        print("LineDetection called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}



      #Keya (Minimum Filter)
      elif opr == 'min_filter':
        output = min_filter(img)
        print("min_filter called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}

   #Jinal (Convolution function)
      elif opr == 'gaussianBlur':
        output = gaussianBlur(img)
        print("gaussianBlur called", output)
        output_url = upload(output)
        
        return  {"output": output_url,"status":True}     



     #Zeel Rathi Watershed Function 
      elif opr == 'watershed':
        output = watershed(img)
        print("watershed called", output)
        output_url = upload(output)

        return  {"output": output_url,"status":True}


    


    if (request.method == "GET"):
      print("got ouput")
      try:
        print("get output", output)
        output_url = upload(output)

        return  {"output": output_url}

      except:
        print("No Input Yet")
      

    return "Image Filter"


app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://cf6d-34-125-186-182.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040
got post request
{'operation': 'canny', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1669291819218000.png?alt=media&token=5bcbc7d4-f319-4dc2-b991-b5845adc35a0'}
canny
canny called [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:18:20] "POST / HTTP/1.1" 200 -


output_url https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/output.jpg?alt=media&token=5fb05dfb-ebe3-4c3e-beb3-2fa385c79774
got post request
{'operation': 'canny', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670383639069000.jpg?alt=media&token=f567aa66-5aa7-46eb-9cb1-ac66a966644c'}
canny
canny called [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:27:31] "POST / HTTP/1.1" 200 -


output_url https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/output.jpg?alt=media&token=6232a1b4-15b8-44a1-8179-f87efb92f0f7
got post request
{'operation': 'min_filter', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670383678601000.jpg?alt=media&token=5f37d7a0-a3f3-4935-ac26-024fd8df3c8a'}
min_filter
min_filter called [[[  3   3   3]
  [  3   3   3]
  [  3   3   3]
  ...
  [  7  13  25]
  [  7  13  25]
  [  7  13  25]]

 [[  3   3   3]
  [  3   3   3]
  [  3   3   3]
  ...
  [  7  13  25]
  [  7  13  25]
  [  7  13  25]]

 [[  3   3   3]
  [  3   3   3]
  [  3   3   3]
  ...
  [  7  13  25]
  [  7  13  25]
  [  7  13  25]]

 ...

 [[  3   2  10]
  [  3   2  10]
  [  3   2  10]
  ...
  [ 24 221 239]
  [ 24 223 241]
  [ 25 226 242]]

 [[  3   2  10]
  [  3   2  10]
  [  3   2  10]
  ...
  [ 25 221 239]
  [ 25 226 241]
  [ 25 228 242]]

 [[  3   2  10]
  [  3   2  10]
  [  3   2  10]
  ...
  [ 30 221 241]
  [ 30 2

INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:29:37] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'bilateral', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385229959000.jpg?alt=media&token=b88a4ab1-b379-44fc-ab59-7bda1e8168d2'}
bilateral
bilateral called [[[110 135 188]
  [108 133 186]
  [117 142 195]
  ...
  [106 140 187]
  [102 137 183]
  [110 144 190]]

 [[112 137 190]
  [117 142 195]
  [107 132 185]
  ...
  [107 142 189]
  [107 141 188]
  [112 146 193]]

 [[111 136 188]
  [118 143 195]
  [119 144 196]
  ...
  [103 138 184]
  [103 138 185]
  [115 149 197]]

 ...

 [[ 12  17  11]
  [ 13  17  11]
  [ 14  18  12]
  ...
  [ 43  54  24]
  [ 48  59  27]
  [ 42  53  22]]

 [[ 13  18  12]
  [ 16  20  14]
  [ 17  21  14]
  ...
  [ 43  55  23]
  [ 49  60  27]
  [ 43  54  22]]

 [[ 15  20  13]
  [ 20  25  17]
  [ 21  26  17]
  ...
  [ 51  62  29]
  [ 58  69  35]
  [ 52  64  30]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:53:57] "POST / HTTP/1.1" 200 -
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-28-5723132af737>", line 167, in convert


got post request
{'operation': 'gaussianBlur', 'img_path': ''}
image path error
gaussianBlur
got post request
{'operation': 'gaussianBlur', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385277656000.PNG?alt=media&token=4db39f12-63b6-4fd5-bfb9-4f259d9ebc38'}
gaussianBlur
gaussianBlur called [[[253 253 253]
  [251 251 251]
  [242 243 243]
  ...
  [191 210 202]
  [194 212 205]
  [196 213 207]]

 [[252 252 252]
  [248 249 248]
  [236 236 236]
  ...
  [167 193 183]
  [172 196 187]
  [174 198 189]]

 [[249 250 250]
  [242 242 242]
  [218 219 219]
  ...
  [113 158 142]
  [121 163 148]
  [125 165 151]]

 ...

 [[245 246 246]
  [233 235 234]
  [199 203 202]
  ...
  [111 137 123]
  [117 143 129]
  [121 146 133]]

 [[249 250 249]
  [242 243 242]
  [221 224 223]
  ...
  [167 183 174]
  [171 187 178]
  [173 189 181]]

 [[251 251 251]
  [245 246 246]
  [230 232 232]
  ...
  [192 204 197]
  [195 206 200]
  [196 207 202]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:54:56] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'rotate', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385353297000.jpg?alt=media&token=e444866a-5c54-4fc9-aed8-83018467af2a'}
rotate
rotate called [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:56:12] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'morphology', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385353297000.jpg?alt=media&token=e444866a-5c54-4fc9-aed8-83018467af2a'}
morphology
morphology called [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:56:40] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'watershed', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385353297000.jpg?alt=media&token=e444866a-5c54-4fc9-aed8-83018467af2a'}
watershed
watershed called [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:56:58] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'smoothing', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385353297000.jpg?alt=media&token=e444866a-5c54-4fc9-aed8-83018467af2a'}
smoothing
smoothing called [[[120  67  35]
  [122  69  36]
  [122  68  36]
  ...
  [ 78  42  20]
  [ 78  42  20]
  [ 79  43  21]]

 [[122  69  36]
  [123  70  36]
  [123  69  36]
  ...
  [ 78  42  20]
  [ 78  42  20]
  [ 78  42  20]]

 [[123  70  37]
  [123  70  37]
  [122  69  36]
  ...
  [ 79  43  21]
  [ 78  42  20]
  [ 78  42  20]]

 ...

 [[  4   2   2]
  [  5   4   2]
  [ 10   4   2]
  ...
  [ 74  42  23]
  [ 75  42  23]
  [ 75  42  23]]

 [[  4   2   2]
  [  5   4   2]
  [ 10   4   2]
  ...
  [ 78  45  26]
  [ 77  44  25]
  [ 77  44  25]]

 [[  5   4   2]
  [  5   4   2]
  [ 10   5   3]
  ...
  [ 78  45  26]
  [ 78  45  26]
  [ 78  45  26]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:57:13] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'LineDetection', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385353297000.jpg?alt=media&token=e444866a-5c54-4fc9-aed8-83018467af2a'}
LineDetection
LineDetection called [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0  53]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0  53]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0  27]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:57:27] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'watershed', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385478425000.jpg?alt=media&token=14fad073-1f58-4a94-b6e0-7a95b2e03326'}
watershed
watershed called [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:58:02] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'smoothing', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385478425000.jpg?alt=media&token=14fad073-1f58-4a94-b6e0-7a95b2e03326'}
smoothing
smoothing called [[[248 248 248]
  [248 248 248]
  [248 248 248]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[248 248 248]
  [248 248 248]
  [248 248 248]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[248 248 248]
  [248 248 248]
  [248 248 248]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 ...

 [[248 248 248]
  [248 248 248]
  [248 248 248]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[248 248 248]
  [248 248 248]
  [248 248 248]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[248 248 248]
  [248 248 248]
  [248 248 248]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 03:58:16] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'LineDetection', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385599517000.jpg?alt=media&token=9e0851c8-9c4c-44f5-b450-e4f2e4617e76'}
LineDetection
LineDetection called [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:00:08] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'thresh', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385646095000.jpg?alt=media&token=d7bbb253-eb7b-4cf4-acb8-38183772a241'}
thresh
thresh called [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:00:58] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'lower_reso', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385646095000.jpg?alt=media&token=d7bbb253-eb7b-4cf4-acb8-38183772a241'}
lower_reso
lower_reso called [[[212 210 209]
  [212 210 209]
  [212 210 209]
  ...
  [212 210 209]
  [211 209 208]
  [211 209 208]]

 [[212 210 209]
  [212 210 209]
  [212 210 209]
  ...
  [212 210 209]
  [212 210 209]
  [212 210 209]]

 [[212 210 209]
  [212 210 209]
  [212 210 209]
  ...
  [212 210 209]
  [212 210 209]
  [211 209 208]]

 ...

 [[211 209 208]
  [211 209 208]
  [212 210 209]
  ...
  [212 210 209]
  [212 210 209]
  [212 210 209]]

 [[212 210 209]
  [212 210 209]
  [212 210 209]
  ...
  [212 210 209]
  [212 210 209]
  [212 210 209]]

 [[212 210 209]
  [212 210 209]
  [212 210 209]
  ...
  [212 210 209]
  [212 210 209]
  [212 210 209]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:01:10] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'thresh', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385699393000.jpg?alt=media&token=e57963c1-08d0-46ef-9007-f82bae5c95ce'}
thresh
thresh called [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:01:47] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'morphology', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385744578000.jpg?alt=media&token=6508fbb4-789d-4b7a-b11a-bb29637fa327'}
morphology
morphology called [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
got post request
{'operation': 'morphology', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appsp

INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:03:03] "POST / HTTP/1.1" 200 -


morphology called [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:03:34] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'morphology', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670385849205000.jpg?alt=media&token=ce30a941-2051-4f09-8d5a-adf06accfa78'}
morphology
morphology called [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:04:25] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'morphology', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670386838259000.jpg?alt=media&token=8df39e3f-5060-4b82-9b93-3d27130911b0'}
morphology
morphology called [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:20:56] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'morphology', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670386838259000.jpg?alt=media&token=8df39e3f-5060-4b82-9b93-3d27130911b0'}
morphology
morphology called [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:21:34] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'morphology', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670386929645000.jpg?alt=media&token=0f8308f1-06fc-4f35-bc09-e736b84f25cc'}
morphology
morphology called [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:22:28] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'bilateral', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670386929645000.jpg?alt=media&token=0f8308f1-06fc-4f35-bc09-e736b84f25cc'}
bilateral
bilateral called [[[110 135 188]
  [108 133 186]
  [117 142 195]
  ...
  [106 140 187]
  [102 137 183]
  [110 144 190]]

 [[112 137 190]
  [117 142 195]
  [107 132 185]
  ...
  [107 142 189]
  [107 141 188]
  [112 146 193]]

 [[111 136 188]
  [118 143 195]
  [119 144 196]
  ...
  [103 138 184]
  [103 138 185]
  [115 149 197]]

 ...

 [[ 12  17  11]
  [ 13  17  11]
  [ 14  18  12]
  ...
  [ 43  54  24]
  [ 48  59  27]
  [ 42  53  22]]

 [[ 13  18  12]
  [ 16  20  14]
  [ 17  21  14]
  ...
  [ 43  55  23]
  [ 49  60  27]
  [ 43  54  22]]

 [[ 15  20  13]
  [ 20  25  17]
  [ 21  26  17]
  ...
  [ 51  62  29]
  [ 58  69  35]
  [ 52  64  30]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:22:36] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'smoothing', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670387032093000.jpg?alt=media&token=7c7759a8-451d-4058-a71d-ff9bf97fb8c6'}
smoothing
smoothing called [[[209 210 212]
  [209 210 212]
  [209 210 212]
  ...
  [208 209 211]
  [208 209 211]
  [208 209 211]]

 [[209 210 212]
  [209 210 212]
  [209 210 212]
  ...
  [209 210 212]
  [209 210 212]
  [209 210 212]]

 [[209 210 212]
  [209 210 212]
  [209 210 212]
  ...
  [209 210 212]
  [209 210 212]
  [209 210 212]]

 ...

 [[209 210 212]
  [209 210 212]
  [209 210 212]
  ...
  [209 210 212]
  [209 210 212]
  [209 210 212]]

 [[209 210 212]
  [209 210 212]
  [209 210 212]
  ...
  [209 210 212]
  [209 210 212]
  [209 210 212]]

 [[209 210 212]
  [209 210 212]
  [209 210 212]
  ...
  [209 210 212]
  [209 210 212]
  [209 210 212]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:24:00] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'thresh', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670387121040000.jpg?alt=media&token=99216d94-ce94-42b5-9c86-fa368c16c9de'}
thresh
thresh called [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:25:27] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'lower_reso', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670387219429000.jpeg?alt=media&token=54ed46a7-138f-4568-bb15-ee42d001a308'}
lower_reso
lower_reso called [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:27:05] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'rotate', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670387374163000.jpg?alt=media&token=52140cba-e454-4024-98dc-7c4886c017a1'}
rotate
rotate called [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:29:41] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'LineDetection', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670387448233000.jpg?alt=media&token=4d6ef2c5-3184-4038-a950-68e941a18fa1'}
LineDetection
LineDetection called [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:30:58] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'gaussianBlur', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670387488343000.PNG?alt=media&token=4e181d95-bfed-4798-a9fd-82e83b3165bf'}
gaussianBlur
gaussianBlur called [[[253 253 253]
  [251 251 251]
  [242 243 243]
  ...
  [191 210 202]
  [194 212 205]
  [196 213 207]]

 [[252 252 252]
  [248 249 248]
  [236 236 236]
  ...
  [167 193 183]
  [172 196 187]
  [174 198 189]]

 [[249 250 250]
  [242 242 242]
  [218 219 219]
  ...
  [113 158 142]
  [121 163 148]
  [125 165 151]]

 ...

 [[245 246 246]
  [233 235 234]
  [199 203 202]
  ...
  [111 137 123]
  [117 143 129]
  [121 146 133]]

 [[249 250 249]
  [242 243 242]
  [221 224 223]
  ...
  [167 183 174]
  [171 187 178]
  [173 189 181]]

 [[251 251 251]
  [245 246 246]
  [230 232 232]
  ...
  [192 204 197]
  [195 206 200]
  [196 207 202]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:31:55] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'min_filter', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670387558209000.jpg?alt=media&token=c9d60165-5c3c-4c6b-bb21-87315ee2becd'}
min_filter
min_filter called [[[ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]
  ...
  [ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]]

 [[ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]
  ...
  [ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]]

 [[ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]
  ...
  [ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]]

 ...

 [[ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]
  ...
  [ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]]

 [[ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]
  ...
  [ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]]

 [[ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]
  ...
  [ 0 13 39]
  [ 0 13 39]
  [ 0 13 39]]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:32:47] "POST / HTTP/1.1" 200 -


got post request
{'operation': 'watershed', 'img_path': 'https://firebasestorage.googleapis.com/v0/b/pixel-e5e96.appspot.com/o/users%2Fuploads%2F1670387625824000.jpg?alt=media&token=6a6a5886-29d1-47f2-b997-7186f5f32c51'}
watershed
watershed called [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


INFO:werkzeug:127.0.0.1 - - [07/Dec/2022 04:33:55] "POST / HTTP/1.1" 200 -
